#!/bin/bash

# VARIABLES
STATE_FILE="$HOME/.config/waybar/Bar_Visible"

# OUTPUT WAYBAR STATUS WITH TOOLTIP
if [ -f "$STATE_FILE" ]; then
	# WAYBAR TOGGLED ON
	echo "{\"text\":\"[ <span font='18'></span> ]\",\"class\":\"active\",\"tooltip\":\"[ WAYBAR - LOCKED ]\"}"
else
	# WAYBAR TOGGLED OFF
	echo "{\"text\":\"[ <span font='18'></span> ]\",\"class\":\"inactive\",\"tooltip\":\"[ WAYBAR - UNLOCKED ]\"}"
fi
